server:
  port: 8082

payment-gateway:
  base-url: http://localhost:9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/payments
    username: payments
    password: payments
  flyway:
    enabled: true
